[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/stats/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/stats/api/event"
  to = "https://plausible.io/api/event"
  status = 200

[dev]
  framework = "astro"